### ISSUE TITLE
Set comment-start

### ISSUE THREAD

**Issue by jscheid** [preetpalS/emacs-dotenv-mode#4]
Can I suggest `(setq-local comment-start "# ")`, it makes `M-;` (`fill-paragraph`) work as expected.

**Comment by preetpalS** [comment]
Thanks for the suggestion. I integrated it into mode. `fill-paragraph` should work as expected now.

**Comment by Fuco1** [comment]
It also makes the `comment-dwim` command to work properly.  I was about to file a pull request, glad to see it's already implemented!
